### ISSUE TITLE
Allowing pull requests

### ISSUE THREAD

**Issue by markwalsh-liverpool** [Ziggeo/ZiggeoCSharpSDK#3]
I've found a bug, in one specific method call, is it possible for you to allow pull request for this repo?

**Comment by oliverfriedmann** [comment]
Of course, pull requests welcome.

**Comment by markwalsh-liverpool** [comment]
I get a 403 when attempting to push my remote branch, do you need to enable collaborators?

**Comment by markwalsh-liverpool** [comment]
Sorry, I was being an idiot, pull request now exists
