### ISSUE TITLE
Installing NUGET package - Newtonsoft.Json dependency error

### ISSUE THREAD

**Issue by markwalsh-liverpool** [Ziggeo/ZiggeoCSharpSDK#5]
When installing the NUGET package I get the following error.

**Attempting to gather dependencies information for package 'ZiggeoCSharpSDK.0.0.6' with respect to project 'werwrwr', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'ZiggeoCSharpSDK.0.0.6' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'Newtownsoft.Json'. Source(s) used: 'nuget.org'.**
========== Finished ==========

**Comment by markwalsh-liverpool** [comment]
I think you'll have to re-publish the NUGET package as version 0.0.6 in Package Manager still has the typo Newtownsoft.Json instead of Newtonsoft.Json

**Comment by markwalsh-liverpool** [comment]
@oliverfriedmann: I think you'll have to re-publish the NUGET package as version 0.0.6 in Package Manager still has the typo Newtownsoft.Json instead of Newtonsoft.Json

**Comment by oliverfriedmann** [comment]
Pushed.
