### ISSUE TITLE
Nuget package contents

### ISSUE THREAD

**Issue by markwalsh-liverpool** [Ziggeo/ZiggeoCSharpSDK#6]
Currently the Nuget package contents for 0.0.7 are just the C# classes.  This really needs to be the compiled .dll file instead so it can be added as a reference.

In the NUSPEC file, this line

```
<file src="src/*" />
```

Should point at your bin folder and reference the ZiggeoCSharpSDK.dll file explicitly.  Once that is pushed to NUGET then we can add Ziggeo as a reference without having to include the source files.

There's no solution file checked in for me to do this myself at the moment.  I can add a pull request with a solution file and reference the correct directory if that helps?

**Comment by oliverfriedmann** [comment]
Please have a look at 0.0.8. Does this release help?

**Comment by markwalsh-liverpool** [comment]
Yep, that's working for me!
